dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "anyulled-github"
    token:
      secure:  sonarToken
jdk:
  - oraclejdk8

language: node_js
cache:
  directories:
    - node_modules
    - '$HOME/.sonar/cache'
notifications:
  email: false
node_js:
  - '8'
install:
- npm install
script: 
- npm run test:coverage
- npm run eslint
- npm run build
- sonar-scanner
after_script:
- npm run coveralls