language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
install:
- npm install
script: 
- npm run test:coverage
- npm run eslint
- npm run build
after_script:
- npm run coveralls